root: true
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
parserOptions:
  project: "./tsconfig.json"
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
rules:
  "@typescript-eslint/no-explicit-any": "off"
  "@typescript-eslint/no-namespace": "off"
  no-case-declarations: "off"
  prefer-const: "warn"
overrides:
  - files: ["bin/**/*.js"]
    env:
      node: true
    parserOptions:
      project: null
    rules:
      "@typescript-eslint/no-var-requires": "off"
